micronaut:
  application:
    name: bookit
  server:
    port: 7777
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - https://localhost:5173

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin
    dialect: POSTGRES
    maximumPoolSize: 5
    connectionTestQuery: SELECT 1
    connectionTimeout: 30000
